repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: nix develop --command isort
        language: system
        types: [python]

    -   id: black
        name: black
        entry: nix develop --command black
        language: system
        types: [python]

    -   id: pylint
        name: pylint
        entry: nix develop --command pylint --rcfile=.pylintrc
        language: system
        types: [python]
        exclude: ^(docs/|tests/)
