name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nix
          echo 'extra-experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf
          echo 'allow-import-from-derivation = false' >> ~/.config/nix/nix.conf
          echo 'eval-cache = false' >> ~/.config/nix/nix.conf
      - name: Run linting
        run: nix develop --option warn-dirty false -c make lint
        env:
          NIX_CONFIG: "extra-experimental-features = nix-command flakes"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nix
          echo 'extra-experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf
          echo 'allow-import-from-derivation = false' >> ~/.config/nix/nix.conf
          echo 'eval-cache = false' >> ~/.config/nix/nix.conf
      - name: Run type checking
        run: nix develop --option warn-dirty false -c make type
        env:
          NIX_CONFIG: "extra-experimental-features = nix-command flakes"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nix
          echo 'extra-experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf
          echo 'allow-import-from-derivation = false' >> ~/.config/nix/nix.conf
          echo 'eval-cache = false' >> ~/.config/nix/nix.conf
      - name: Run tests
        run: nix develop --option warn-dirty false -c make test
        env:
          NIX_CONFIG: "extra-experimental-features = nix-command flakes"