name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      # Use GitHub's own cache action instead of the DeterminateSystems one
      - uses: actions/cache@v4
        name: Cache Nix store
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-
            
      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nix
          echo 'extra-experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf
          echo 'allow-import-from-derivation = false' >> ~/.config/nix/nix.conf
          echo 'eval-cache = false' >> ~/.config/nix/nix.conf
          echo 'warn-dirty = false' >> ~/.config/nix/nix.conf
          # Disable binary cache to avoid HTTP 418 errors
          echo 'substitute = false' >> ~/.config/nix/nix.conf
          
      - name: Run linting
        run: nix --quiet develop -c make lint
        env:
          NIX_CONFIG: "extra-experimental-features = nix-command flakes"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      # Use GitHub's own cache action instead of the DeterminateSystems one
      - uses: actions/cache@v4
        name: Cache Nix store
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-
            
      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nix
          echo 'extra-experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf
          echo 'allow-import-from-derivation = false' >> ~/.config/nix/nix.conf
          echo 'eval-cache = false' >> ~/.config/nix/nix.conf
          echo 'warn-dirty = false' >> ~/.config/nix/nix.conf
          # Disable binary cache to avoid HTTP 418 errors
          echo 'substitute = false' >> ~/.config/nix/nix.conf
          
      - name: Run type checking
        run: nix --quiet develop -c make type
        env:
          NIX_CONFIG: "extra-experimental-features = nix-command flakes"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      # Use GitHub's own cache action instead of the DeterminateSystems one  
      - uses: actions/cache@v4
        name: Cache Nix store
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-
            
      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nix
          echo 'extra-experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf
          echo 'allow-import-from-derivation = false' >> ~/.config/nix/nix.conf
          echo 'eval-cache = false' >> ~/.config/nix/nix.conf
          echo 'warn-dirty = false' >> ~/.config/nix/nix.conf
          # Disable binary cache to avoid HTTP 418 errors
          echo 'substitute = false' >> ~/.config/nix/nix.conf
          
      - name: Run tests
        run: nix --quiet develop -c make test
        env:
          NIX_CONFIG: "extra-experimental-features = nix-command flakes"